{{- if .Values.duckling.enabled }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "duckling.host" . }}
  labels:
    {{- include "rasa-x.labels" . | nindent 4 }}
    app.kubernetes.io/component: duckling
{{- with .Values.duckling.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ports:
  - port: {{ .Values.duckling.port }}
    targetPort: {{ .Values.duckling.port }}
    protocol: "TCP"
  selector:
    {{- include "rasa-x.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: duckling
{{- end }}
