{{if and .Values.separateEventService (eq .Values.separateEventService "true") }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Release.Name }}-event-service
  labels:
    {{- include "rasa-x.labels" . | nindent 4 }}
    app.kubernetes.io/component: event-service
spec:
  progressDeadlineSeconds: {{ .Values.global.progressDeadlineSeconds }}
  replicas: {{ default 1 .Values.eventService.replicaCount }}
  selector:
    matchLabels:
      {{- include "rasa-x.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: event-service
  template:
    metadata:
      labels:
        {{- include "rasa-x.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: event-service
        {{- if .Values.eventService.podLabels }}
{{ toYaml .Values.eventService.podLabels | indent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.eventService.automountServiceAccountToken }}
      {{ include "rasa-x.spec" . }}
      {{- if .Values.eventService.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.eventService.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.eventService.tolerations }}
      tolerations:
{{ toYaml .Values.eventService.tolerations | indent 6 }}
      {{- end }}
      # Use the init-db init container to check if database migration is completed.
      # The event service uses a database, to make sure that the database is ready
      # to use we use the database migration service to check migration status.
      {{- $image := printf "%s:%s" .Values.eventService.name (.Values.eventService.tag | default (include "rasa-x.version" .)) -}}
      {{- include "initContainer.dbMigration" (dict "context" $ "image" $image ) |  nindent 6 }}

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.eventService.name }}:{{ .Values.eventService.tag | default (include "rasa-x.version" .) }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        {{- if .Values.eventService.command }}
        command:
          {{- toYaml .Values.eventService.command | nindent 10 }}
        {{- end }}
        args:
          {{- if .Values.eventService.args }}
          {{- toYaml .Values.eventService.args | nindent 10 }}
          {{- else }}
          - python
          - -m
          - rasax.community.services.event_service
          {{- end }}
        ports:
          - name: "http"
            containerPort: {{ default 5673 .Values.eventService.port }}
            protocol: "TCP"
        {{- if or .Values.eventService.livenessProbe.enabled (not (hasKey .Values.eventService.livenessProbe "enabled")) }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.eventService.livenessProbe.initialProbeDelay }}
          httpGet:
            path: "/health"
            port: "http"
            scheme: {{ default "HTTP" .Values.eventService.livenessProbe.scheme }}
        {{ end }}
        {{- if or .Values.eventService.readinessProbe.enabled (not (hasKey .Values.eventService.readinessProbe "enabled")) }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.eventService.readinessProbe.initialProbeDelay }}
          httpGet:
            path: "/health"
            port: "http"
            scheme: {{ default "HTTP" .Values.eventService.readinessProbe.scheme }}
        {{ end }}
        env:
        {{- if eq "true" (include "is_enterprise" .) }}
        - name: "RASA_TELEMETRY_ENABLED"
          value: "false"
        {{ end }}
        - name: "SELF_PORT"
          value: {{ default 5673 .Values.eventService.port | quote }}
        {{- if $.Values.rabbitmq.enabled }}
        - name: "RABBITMQ_QUEUE"
          value: {{ template "rasa-x.rabbitmq.queue" . }}
        - name: "RABBITMQ_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ template "rasa-x.rabbitmq.password.secret" . }}
              key: {{ template "rasa-x.rabbitmq.password.key" . }}
        {{ end }}
        {{- if $.Values.redis.install }}
        - name: "REDIS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ template "rasa-x.redis.password.secret" $ }}
              key: {{ template "rasa-x.redis.password.key" $ }}
        {{- end }}
        - name: "RASA_X_USER_ANALYTICS"
          value: "0"
        - name: "LOCAL_MODE" # This variable doesn't do anything anymore in Rasa X 0.28 and later
          value: "false"
        {{- include "rasa-x.psql.envs" . | nindent 8 }}
        {{- include "rasax.event-service.extra.envs" . | nindent 8 }}
        {{- with .Values.eventService.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
{{- if .Values.eventService.extraVolumeMounts }}
{{ toYaml .Values.eventService.extraVolumeMounts | indent 8 }}
{{- end }}
        - mountPath: "/app/endpoints.yml"
          subPath: "endpoints.yml"
          name: "rasa-configuration"
      volumes:
{{- if .Values.eventService.extraVolumes }}
{{ toYaml .Values.eventService.extraVolumes | indent 6 }}
{{- end }}
      - name: "rasa-configuration"
        configMap:
          name: {{ template "rasa-x.rasa.configuration-files" . }}
          items:
            - key: "rasa-endpoints"
              path: "endpoints.yml"
{{end}}
