# Only generate secret if no externalSecret was provided.
{{ if not .Values.rasaSecret }}

apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ template "rasa-x.secret" . }}
type: "Opaque"
data:
  rasaToken: {{ .Values.rasa.token | b32enc | quote }}
  rasaXToken: {{ .Values.rasax.token | b32enc | quote }}
  passwordSalt: {{ .Values.rasax.passwordSalt | b32enc | quote }}
  jwtSecret: {{ .Values.rasax.jwtSecret | b64enc | quote }}
  initialPassword: {{ .Values.rasax.initialUser.password | b64enc | quote }}
{{ end }}
