apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nginx
spec:
  rules:
  - host: example.test.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /