# helmfile for Rasa X deployment
releases:
  - name: {{ requiredEnv "RELEASE_NAME" }}
    namespace: {{ requiredEnv "NAMESPACE" }}
    labels:
        release: {{ requiredEnv "RELEASE_NAME" }}
    chart: rasa-x/rasa-x
    values:
      - nginx:
          enabled: false
      - ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/enable-cors: "true"
          hosts:
            - host: {{ requiredEnv "DOMAIN" }}
              paths:
                - /
