# helmfile for Rasa X deployment
releases:
  - name: "rasa-x"
    chart: rasa-x/rasa-x
    values:
      - nginx:
          enabled: false
      - ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/enable-cors: "true"
          hosts:
            - host: example.test.com
              paths:
                - /
