# helmfile for Rasa X deployment
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: rasa-x
    namespace: default
    chart: ../../charts/rasa-x
    values:
      - rasax:
          disableTelemetry: true
          initialUser:
            password: {{ requiredEnv "INITIAL_USER_PASSWORD" }}
      - duckling:
          enabled: false
      - nginx:
          enabled: false
      - ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/enable-cors: "true"
          hosts:
            - host: rasa-x.test.com
              paths:
                - /
